name: 'ONES Performance'
description: 'Performance Test Action'
icon: activity
color: purple
inputs:
  websites:
    description: 'websites：需要测试的网站链接。用,分割'
    required: true
  iterations: 
    description: 'Run Number'
    type: number
    default: 5
    required: true
  sitespeed:
    description: 'Run SiteSpeed Performance Scripts'
    required: true
    type: boolean
    default: true
  lighthouse:
    description: 'Run Lighthouse Performance Scripts'
    required: true
    type: boolean
    default: false
  cookies:
    description: '传入的 Cookies, 用;分割'
    type: string
    default: ''
  preset:
    description: 'Preset，可选值: [desktop|mobile]'
    required: true
    type: string
    default: 'desktop'
runs:
  using: 'node16'
  main: 'src/action.js'